LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ifneq (,$(filter $(TARGET_ARCH), x86 x86_64))
    MAGISKBOOT_TARGET := magiskbootx86
else
    MAGISKBOOT_TARGET := magiskbootarm
endif
#magiskboot prebuilt
include $(CLEAR_VARS)
LOCAL_MODULE := magiskboot
LOCAL_MODULE_OWNER := lineage
LOCAL_SRC_FILES := $(MAGISKBOOT_TARGET)
LOCAL_MODULE_STEM := magiskboot
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)
LOCAL_OVERRIDES_PACKAGES := su
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
